from enum import StrEnum


class ErrorCode(StrEnum):
    INVALID_OTP = "INVALID_OTP"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    ACCOUNT_INACTIVE = "ACCOUNT_INACTIVE"

    SESSION_EXPIRED = "SESSION_EXPIRED"
    TERMINATE_CURRENT_SESSION = "TERMINATE_CURRENT_SESSION"

    SMTP_ERROR = "SMTP_ERROR"

    USER_NOT_FOUND = "USER_NOT_FOUND"

    AUTH_REQUIRED = "AUTH_REQUIRED"
    AUTH_TOO_MANY_REQUESTS = "AUTH_TOO_MANY_REQUESTS"
    PERMISSION_DENIED = "PERMISSION_DENIED"

    NOT_FOUND = "NOT_FOUND"
    CONFLICT = "CONFLICT"
    BAD_REQUEST = "BAD_REQUEST"

